function [T1,T2,T3,FK] = FK3RDHMTH(alpha, a, theta, d)
%Função que computa a cinemática direta de um manipulador 3R planar.
%A modelagem deve ser feita por parâmetros Denavit-Hartenberg e a álgebra por Matrizes de Transformação Homogêneas.

alpha1 = alpha(1);
alpha2 = alpha(2);
alpha3 = alpha(3);

a1 = a(1);
a2 = a(2);
a3 = a(3);

theta1 = theta(1);
theta2 = theta(2);
theta3 = theta(3);

d1 = d(1);
d2 = d(2);
d3 = d(3);

T1 = eye(4);

T2 = [ cos(theta1), -cos(alpha1)*sin(theta1),  sin(alpha1)*sin(theta1), a1*cos(theta1);
       sin(theta1),  cos(alpha1)*cos(theta1), -sin(alpha1)*cos(theta1), a1*sin(theta1);
                 0,              sin(alpha1),              cos(alpha1),             d1;
                 0,                        0,                        0,              1];
             
T3 = [ cos(theta1)*cos(theta2) - cos(alpha1)*sin(theta1)*sin(theta2), sin(alpha1)*sin(alpha2)*sin(theta1) - cos(alpha2)*cos(theta1)*sin(theta2) - cos(alpha1)*cos(alpha2)*cos(theta2)*sin(theta1), cos(alpha2)*sin(alpha1)*sin(theta1) + sin(alpha2)*cos(theta1)*sin(theta2) + cos(alpha1)*sin(alpha2)*cos(theta2)*sin(theta1), a1*cos(theta1) + a2*cos(theta1)*cos(theta2) + d2*sin(alpha1)*sin(theta1) - a2*cos(alpha1)*sin(theta1)*sin(theta2);
       cos(theta2)*sin(theta1) + cos(alpha1)*cos(theta1)*sin(theta2), cos(alpha1)*cos(alpha2)*cos(theta1)*cos(theta2) - cos(alpha2)*sin(theta1)*sin(theta2) - sin(alpha1)*sin(alpha2)*cos(theta1), sin(alpha2)*sin(theta1)*sin(theta2) - cos(alpha2)*sin(alpha1)*cos(theta1) - cos(alpha1)*sin(alpha2)*cos(theta1)*cos(theta2), a1*sin(theta1) - d2*sin(alpha1)*cos(theta1) + a2*cos(theta2)*sin(theta1) + a2*cos(alpha1)*cos(theta1)*sin(theta2);
                                         sin(alpha1)*sin(theta2),                                                               cos(alpha1)*sin(alpha2) + cos(alpha2)*sin(alpha1)*cos(theta2),                                                               cos(alpha1)*cos(alpha2) - sin(alpha1)*sin(alpha2)*cos(theta2),                                                                  d1 + d2*cos(alpha1) + a2*sin(alpha1)*sin(theta2);
                                                               0,                                                                                                                           0,                                                                                                                           0,                                                                                                                 1];

FK = [ cos(theta3)*(cos(theta1)*cos(theta2) - cos(alpha1)*sin(theta1)*sin(theta2)) - sin(theta3)*(cos(alpha2)*cos(theta1)*sin(theta2) - sin(alpha1)*sin(alpha2)*sin(theta1) + cos(alpha1)*cos(alpha2)*cos(theta2)*sin(theta1)),   sin(alpha3)*(cos(alpha2)*sin(alpha1)*sin(theta1) + sin(alpha2)*cos(theta1)*sin(theta2) + cos(alpha1)*sin(alpha2)*cos(theta2)*sin(theta1)) - cos(alpha3)*sin(theta3)*(cos(theta1)*cos(theta2) - cos(alpha1)*sin(theta1)*sin(theta2)) - cos(alpha3)*cos(theta3)*(cos(alpha2)*cos(theta1)*sin(theta2) - sin(alpha1)*sin(alpha2)*sin(theta1) + cos(alpha1)*cos(alpha2)*cos(theta2)*sin(theta1)), cos(alpha3)*(cos(alpha2)*sin(alpha1)*sin(theta1) + sin(alpha2)*cos(theta1)*sin(theta2) + cos(alpha1)*sin(alpha2)*cos(theta2)*sin(theta1)) + sin(alpha3)*sin(theta3)*(cos(theta1)*cos(theta2) - cos(alpha1)*sin(theta1)*sin(theta2)) + sin(alpha3)*cos(theta3)*(cos(alpha2)*cos(theta1)*sin(theta2) - sin(alpha1)*sin(alpha2)*sin(theta1) + cos(alpha1)*cos(alpha2)*cos(theta2)*sin(theta1)), a1*cos(theta1) + d3*(cos(alpha2)*sin(alpha1)*sin(theta1) + sin(alpha2)*cos(theta1)*sin(theta2) + cos(alpha1)*sin(alpha2)*cos(theta2)*sin(theta1)) + a2*cos(theta1)*cos(theta2) + d2*sin(alpha1)*sin(theta1) - a3*sin(theta3)*(cos(alpha2)*cos(theta1)*sin(theta2) - sin(alpha1)*sin(alpha2)*sin(theta1) + cos(alpha1)*cos(alpha2)*cos(theta2)*sin(theta1)) + a3*cos(theta3)*(cos(theta1)*cos(theta2) - cos(alpha1)*sin(theta1)*sin(theta2)) - a2*cos(alpha1)*sin(theta1)*sin(theta2);
       cos(theta3)*(cos(theta2)*sin(theta1) + cos(alpha1)*cos(theta1)*sin(theta2)) - sin(theta3)*(sin(alpha1)*sin(alpha2)*cos(theta1) + cos(alpha2)*sin(theta1)*sin(theta2) - cos(alpha1)*cos(alpha2)*cos(theta1)*cos(theta2)), - sin(alpha3)*(cos(alpha2)*sin(alpha1)*cos(theta1) - sin(alpha2)*sin(theta1)*sin(theta2) + cos(alpha1)*sin(alpha2)*cos(theta1)*cos(theta2)) - cos(alpha3)*sin(theta3)*(cos(theta2)*sin(theta1) + cos(alpha1)*cos(theta1)*sin(theta2)) - cos(alpha3)*cos(theta3)*(sin(alpha1)*sin(alpha2)*cos(theta1) + cos(alpha2)*sin(theta1)*sin(theta2) - cos(alpha1)*cos(alpha2)*cos(theta1)*cos(theta2)), sin(alpha3)*sin(theta3)*(cos(theta2)*sin(theta1) + cos(alpha1)*cos(theta1)*sin(theta2)) - cos(alpha3)*(cos(alpha2)*sin(alpha1)*cos(theta1) - sin(alpha2)*sin(theta1)*sin(theta2) + cos(alpha1)*sin(alpha2)*cos(theta1)*cos(theta2)) + sin(alpha3)*cos(theta3)*(sin(alpha1)*sin(alpha2)*cos(theta1) + cos(alpha2)*sin(theta1)*sin(theta2) - cos(alpha1)*cos(alpha2)*cos(theta1)*cos(theta2)), a1*sin(theta1) - d3*(cos(alpha2)*sin(alpha1)*cos(theta1) - sin(alpha2)*sin(theta1)*sin(theta2) + cos(alpha1)*sin(alpha2)*cos(theta1)*cos(theta2)) - d2*sin(alpha1)*cos(theta1) - a3*sin(theta3)*(sin(alpha1)*sin(alpha2)*cos(theta1) + cos(alpha2)*sin(theta1)*sin(theta2) - cos(alpha1)*cos(alpha2)*cos(theta1)*cos(theta2)) + a2*cos(theta2)*sin(theta1) + a3*cos(theta3)*(cos(theta2)*sin(theta1) + cos(alpha1)*cos(theta1)*sin(theta2)) + a2*cos(alpha1)*cos(theta1)*sin(theta2);
                                                                                                             sin(theta3)*(cos(alpha1)*sin(alpha2) + cos(alpha2)*sin(alpha1)*cos(theta2)) + sin(alpha1)*cos(theta3)*sin(theta2),                                                                                                                                                                       sin(alpha3)*(cos(alpha1)*cos(alpha2) - sin(alpha1)*sin(alpha2)*cos(theta2)) + cos(alpha3)*cos(theta3)*(cos(alpha1)*sin(alpha2) + cos(alpha2)*sin(alpha1)*cos(theta2)) - cos(alpha3)*sin(alpha1)*sin(theta2)*sin(theta3),                                                                                                                                                                     cos(alpha3)*(cos(alpha1)*cos(alpha2) - sin(alpha1)*sin(alpha2)*cos(theta2)) - sin(alpha3)*cos(theta3)*(cos(alpha1)*sin(alpha2) + cos(alpha2)*sin(alpha1)*cos(theta2)) + sin(alpha1)*sin(alpha3)*sin(theta2)*sin(theta3),                                                                                                                                                                                                                                      d1 + d2*cos(alpha1) + d3*(cos(alpha1)*cos(alpha2) - sin(alpha1)*sin(alpha2)*cos(theta2)) + a2*sin(alpha1)*sin(theta2) + a3*sin(theta3)*(cos(alpha1)*sin(alpha2) + cos(alpha2)*sin(alpha1)*cos(theta2)) + a3*sin(alpha1)*cos(theta3)*sin(theta2);
                                                                                                                                                                                                                             0,                                                                                                                                                                                                                                                                                                                                                                                             0,                                                                                                                                                                                                                                                                                                                                                                                           0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1];

end
